Adds SPA sample app to the repository
BentleySystems/ES-API-Samples pull request #12
Opened 2023-08-08 15:04 UTC by cobenatben

Adds an additional sample app which is an SPA to the repository. Primarily React based.

2023-08-09 03:33 UTC, Xellon commented
Please rebase to master, old changes that are already commited are shown as new here

2023-08-09 14:45 UTC, cobenatben commented
> Please rebase to master, old changes that are already commited are shown as new here
Rebased, but it seems like these changes are still showing up/there are now even further changes which were not there previously

2023-08-10 03:29 UTC, Xellon commented
> > Please rebase to master, old changes that are already commited are shown as new here
> 
> Rebased, but it seems like these changes are still showing up/there are now even further changes which were not there previously

Files changed tab looks ok now.

2023-08-10 05:02 UTC, Xellon requested changes

2023-08-10 05:02 UTC, Xellon commented on EsApi4DScheduleSPASampleApp/src/App.tsx
> +    } catch (err: any) {
this catch is kind of useless, you're not awaiting Axios.get

2023-08-10 07:38 UTC, cobenatben commented on EsApi4DScheduleSPASampleApp/src/App.tsx
> +      headers: { Authorization: tok }
The way we get the token is by using authClient.getAccessToken(), which is provided by @itwin/browser-authorization package. It returns something like "Bearer ey<etc etc>"

2023-08-10 07:48 UTC, cobenatben commented on EsApi4DScheduleSPASampleApp/src/App.tsx
> +    const decodedToken = await jwt_decode(token) as any;
This function does not always refresh the token, it checks to see if the token is expired and if so, it will refresh it

2023-08-10 07:50 UTC, Xellon commented on EsApi4DScheduleSPASampleApp/src/App.tsx
> +    const decodedToken = await jwt_decode(token) as any;
I meant that you're duplicating code in each request that should be in a timer. If you don't want to use a timer at least put refresh check in a function

2023-08-10 08:32 UTC, Xellon approved these changes

2023-08-10 08:44 UTC, merged